spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_USERS_URL}
    username: ${DB_USERS_USER}
    password: ${DB_USERS_PASS}
    driver-class-name: ${DB_USERS_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

credentials:
  user: ${CREDENTIALS_USERS_USER:1}
  password: ${CREDENTIALS_USERS_PASS:1}

microservices:
  auth:
    base-url: ${URL_AUTH_MS}
