apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: usersuser
  MYSQL_PASSWORD: userspass
  MYSQL_DATABASE: usersdb



#data:
#  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=   # "rootpass"
#  MYSQL_USER: dXNlcnN1c2Vy           # "usersuser"
#  MYSQL_PASSWORD: dXNlcnNwYXNz       # "userspass"
#  MYSQL_DATABASE: dXNlcnNkYg==       # "usersdb"