apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallet-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: wallet.local
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
          - path: /accounts/?(.*)
            pathType: Prefix
            backend:
              service:
                name: accounts-service
                port:
                  number: 8080
          - path: /transactions/?(.*)
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8080
          - path: /users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 8080
