global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'users-service'
    static_configs:
      - targets: [ 'users-service:8080' ]
    metrics_path: /actuator/prometheus

  - job_name: 'accounts-service'
    static_configs:
      - targets: [ 'accounts-service:8080' ]
    metrics_path: /actuator/prometheus

  - job_name: 'transactions-service'
    static_configs:
      - targets: [ 'transactions-service:8080' ]
    metrics_path: /actuator/prometheus
