apiVersion: v1
kind: Secret
metadata:
  name: transactions-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: transactionsuser
  MYSQL_PASSWORD: transactionspass
  MYSQL_DATABASE: transactionsdb
