spring:
  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

credentials:
  user: ${CREDENTIALS_USER:1}
  password: ${CREDENTIALS_PASS:1}

jwt:
  secret: ${JWT_SECRET:myXSuperXSecretXKeyX32charsMinmyXSuperXSecretXKeyX32charsMinX2}
  duration-minutes: ${JWT_SECRET_DURATION:10}

microservices:
  users:
    base-url: ${MS_USERS_BASE_URL:'http://USERS/api'}
    credentials: ${MS_USERS_CREDENTIALS:'1:1'}
  transactions:
    base-url: ${MS_TRANSACTIONS_BASE_URL:'http://TRANSACTIONS/api/transactions'}
    credentials: ${MS_TRANSACTIONS_CREDENTIALS:'1:1'}
  accounts:
    base-url: ${MS_ACCOUNTS_BASE_URL:'http://ACCOUNTS/api/accounts'}
    credentials: ${MS_ACCOUNTS_CREDENTIALS:'1:1'}
  auth:
    base-url: ${MS_AUTH_BASE_URL:'http://AUTH/api/auth'}
    credentials: ${MS_ACCOUNTS_CREDENTIALS:'1:1'}