spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_TRANSACTIONS_URL}
    username: ${DB_TRANSACTIONS_USER}
    password: ${DB_TRANSACTIONS_PASS}
    driver-class-name: ${DB_TRANSACTIONS_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: ${RABBITMQ_DOCKER_CONTAINER_NAME}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

microservices:
  auth:
    base-url: ${URL_AUTH_MS}
  accounts:
    base-url: ${URL_ACCOUNTS_MS}