apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: accountsuser
  MYSQL_PASSWORD: accountspass
  MYSQL_DATABASE: accountsdb
