apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://accounts-db:3306/accountsdb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
