apiVersion: v1
kind: Secret
metadata:
  name: accounts-secrets
type: Opaque
#data:
#  SPRING_DATASOURCE_USERNAME: dXNlcnN1c2Vy   # base64 de "usersuser"
#  SPRING_DATASOURCE_PASSWORD: dXNlcnNwYXNz # base64 de "userspass"

stringData:
  SPRING_DATASOURCE_USERNAME: accountsuser
  SPRING_DATASOURCE_PASSWORD: accountspass
